fix hard coded return_per_1000
RaoFoundation/subtensor pull request #1015
Opened 2024-11-25 14:25 UTC by open-junius

## Description
To fix the issue #992 

## Related Issue(s)

- Closes #[992]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-11-25 16:32 UTC, sam0x17 approved these changes, later dismissed

2024-11-27 01:46 UTC, cuteolaf reviewed
looks good to me.
what about to add a test?

2024-11-27 13:37 UTC, open-junius commented
> looks good to me. what about to add a test?
will check how to test rpc function

2024-12-05 23:55 UTC, gztensor requested changes

2024-12-05 23:55 UTC, gztensor commented on pallets/subtensor/src/rpc_info/delegate_info.rs
> +                .saturating_mul(U64F64::from_num(u16::MAX.saturating_sub(take.0)))
Can we use `.into()` here to be more idiomatic?

2025-01-10 20:59 UTC, sam0x17 approved these changes

2025-01-10 20:59 UTC, merged