[hotfix] Fix set children rate limit
RaoFoundation/subtensor pull request #1037
Opened 2024-11-28 19:34 UTC by camfairchild

## Description

This PR hotfixes the set_children rate limit of 2 tempos for a specific subnet.
Includes a test for the hotfix.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-11-28 19:36 UTC, sam0x17 approved these changes

2024-11-28 20:34 UTC, distributedstatemachine requested changes
this change breaks alot of the existing tests .

```shell

failures:
    test_do_revoke_child_singular_success
    test_do_revoke_children_multiple_complex_scenario
    test_do_revoke_children_multiple_non_existent_children
    test_do_revoke_children_multiple_partial_revocation
    test_do_revoke_children_multiple_success
    test_do_set_child_singular_multiple_children
    test_do_set_child_singular_old_children_cleanup
    test_do_set_child_singular_proportion_edge_cases
    test_do_set_children_multiple_old_children_cleanup
    test_do_set_children_multiple_overwrite_existing
  ```
  
  can you please patch these ?

2024-11-28 22:05 UTC, camfairchild commented
> this change breaks alot of the existing tests .
> 
> ```shell
> failures:
>     test_do_revoke_child_singular_success
>     test_do_revoke_children_multiple_complex_scenario
>     test_do_revoke_children_multiple_non_existent_children
>     test_do_revoke_children_multiple_partial_revocation
>     test_do_revoke_children_multiple_success
>     test_do_set_child_singular_multiple_children
>     test_do_set_child_singular_old_children_cleanup
>     test_do_set_child_singular_proportion_edge_cases
>     test_do_set_children_multiple_old_children_cleanup
>     test_do_set_children_multiple_overwrite_existing
> ```
> 
> can you please patch these ?

Should be fixed with new `step_rate_limit` helper

2024-11-29 17:17 UTC, gztensor approved these changes

2024-11-29 17:22 UTC, distributedstatemachine approved these changes

2024-11-29 19:08 UTC, unconst approved these changes

2024-11-29 19:08 UTC, merged