[WIP] Subnet hyperparameter
RaoFoundation/subtensor pull request #1089
Opened 2024-12-11 15:36 UTC by open-junius

## Description
It will fix the ticket #1067 

## Related Issue(s)

- Closes #[1067]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-12-13 12:48 UTC, open-junius commented
E2E test case https://github.com/opentensor/subtensor-js-tests/blob/main/src/evm/eth.subnet.test.js

2024-12-16 16:40 UTC, gztensor approved these changes

2024-12-16 16:47 UTC, gztensor requested changes

2024-12-16 16:47 UTC, gztensor commented on runtime/src/precompiles/subnet.rs
> +pub const STAKING_CONTRACT_ADDRESS: &str = "5DPSUCb5mZFfizvBDSnRoAqmxV5Bmov2CS3xV773qU6VP1w2";
This should be named SUBNET_CONTRACT_ADDRESS

2025-02-10 16:34 UTC, gztensor approved these changes

2025-02-10 16:35 UTC, sam0x17 approved these changes

2025-02-10 16:36 UTC, merged