Fix/pending childkeys
RaoFoundation/subtensor pull request #1109
Opened 2024-12-19 23:17 UTC by gztensor

## Description
Fixes two issues:

1. When sn registrations are disabled, pending childkeys are not applied
2. Unable to revoke childkeys when stake is below minimum

## Related Issue(s)

n/a

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-19 23:32 UTC, camfairchild requested changes

2024-12-19 23:32 UTC, camfairchild commented on pallets/subtensor/src/tests/children.rs
> +fn test_do_set_child_min_stake_check() {
duplicate? of L3636

2024-12-19 23:47 UTC, camfairchild commented on pallets/subtensor/src/tests/children.rs
> +}
```suggestion
```

2024-12-20 00:44 UTC, camfairchild approved these changes

2024-12-20 17:42 UTC, sam0x17 approved these changes

2024-12-20 17:54 UTC, merged