[WIP] add subnets precompile
RaoFoundation/subtensor pull request #1110
Opened 2024-12-20 10:49 UTC by open-junius

## Description

## Related Issue(s)

- Closes #[1075]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-12-20 12:41 UTC, open-junius commented
https://github.com/opentensor/subtensor-js-tests/blob/main/src/evm/eth.subnets.test.js e2e test case added.

2025-01-17 14:24 UTC, gztensor requested changes

2025-01-17 14:24 UTC, gztensor commented on runtime/src/precompiles/solidity/subnets.sol
> +interface ISubnets {
This naming is a bit confusing. Please rename `ISubnets` to `INeuron` and files: `subnets.sol/abi` to `neuron.sol/abi`.

2025-01-29 00:03 UTC, gztensor commented on runtime/src/precompiles/neuron.rs
> +    fn parse_netuid_hotkey_parameter(data: &[u8]) -> Result<(u16, [u8; 32]), PrecompileFailure> {
Could you please move `parse_pub_key` and `parse_netuid` to the common space like you did with `dispatch`, for example, and use them here?

2025-01-29 00:03 UTC, gztensor commented on runtime/src/precompiles/subnet.rs
> +        let subnet_name_len: usize = u32::from_be_bytes(buf) as usize;
What happens if user passes 0xFFFF size?
Also, what happens if data size is lower than subent_name_len? 
We should gracefully handle this without panics.

2025-01-30 10:35 UTC, open-junius commented on runtime/src/precompiles/subnet.rs
> +        let subnet_name_len: usize = u32::from_be_bytes(buf) as usize;
will add check for all items' length.

2025-01-30 10:38 UTC, open-junius commented on runtime/src/precompiles/neuron.rs
> +    fn parse_netuid_hotkey_parameter(data: &[u8]) -> Result<(u16, [u8; 32]), PrecompileFailure> {
moved both functions to mod

2025-01-30 17:04 UTC, gztensor approved these changes

2025-01-30 17:28 UTC, sam0x17 approved these changes

2025-01-30 17:29 UTC, merged