add utility pallet into runtime
RaoFoundation/subtensor pull request #125
Opened 2023-04-28 22:34 UTC by cuteolaf

2023-04-29 17:58 UTC, Rubberbandits commented on runtime/src/lib.rs
Please leave the tabulation as is for the majority of the file

2023-04-29 18:00 UTC, Rubberbandits requested changes

2023-04-29 18:00 UTC, Rubberbandits commented on runtime/src/lib.rs
> +    spec_version: 119,
spec_version needs to be +1 for chain upgrades

2023-04-29 18:34 UTC, camfairchild commented
What steps have been done to test the integration?

2023-04-30 02:19 UTC, Rubberbandits requested changes

2023-04-30 02:19 UTC, Rubberbandits commented on runtime/src/lib.rs
> +    spec_version: 119,
Not resolved

2023-04-30 22:40 UTC, cuteolaf commented
> What steps have been done to test the integration?

https://github.com/opentensor/subtensor/pull/125/commits/218ee7430735dbb3145d0e9a1b983a96fe7c1f07

2023-05-01 20:16 UTC, Rubberbandits approved these changes
LGTM

2023-05-01 23:22 UTC, camfairchild approved these changes
LGTM. 
Thanks for the contribution 😁

2023-05-03 14:43 UTC, shibshib commented
Merged to mainnet @block 315,568 and testnet @block 267,113

2023-05-03 14:43 UTC, merged