Add local chain to chain_spec for fast testing with localnet
RaoFoundation/subtensor pull request #153
Opened 2023-06-23 01:26 UTC by Rubberbandits

Previously using `test_finney` or `finney` chains when generating a chain-spec, Alice and Bob keys aren't inserted as initial authorities. This PR adds a third chain, `local` which has the correct initial authorities and balances for all development keys in `polkadot.js`

2023-06-23 15:24 UTC, shibshib approved these changes

2023-06-26 20:47 UTC, camfairchild commented on node/src/chain_spec.rs
> +			key: Some(Ss58Codec::from_ss58check("5GpzQgpiAKHMWNSH3RN4GLf96GVTDct9QxYEFAY7LWcVzTbx").unwrap()),
Is this for local development? What key is this?

2023-06-26 20:53 UTC, Rubberbandits commented on node/src/chain_spec.rs
> +			key: Some(Ss58Codec::from_ss58check("5GpzQgpiAKHMWNSH3RN4GLf96GVTDct9QxYEFAY7LWcVzTbx").unwrap()),
This is the same as finney testnet sudo

2023-06-26 21:29 UTC, camfairchild requested changes

2023-06-26 21:29 UTC, camfairchild commented on node/src/chain_spec.rs
> +			key: Some(Ss58Codec::from_ss58check("5GpzQgpiAKHMWNSH3RN4GLf96GVTDct9QxYEFAY7LWcVzTbx").unwrap()),
```suggestion
			key: Some(get_account_id_from_seed::<sr25519::Public>("Alice")),
```

2023-06-26 21:30 UTC, camfairchild approved these changes

2023-06-26 21:46 UTC, merged