Move event deposits into delegated storage setters
RaoFoundation/subtensor pull request #163
Opened 2023-07-11 19:13 UTC by Rubberbandits

## Description

This change moves all storage-setter related event deposits into the delegated function, allowing events to be emitted when the runtime changes storage values outside of sudo calls.

______

## Checklist

- [X] No _new_ compiler warnings

2023-07-11 20:04 UTC, camfairchild requested changes
We should add a check to each test for these calls that each event is emitted, as expected

2023-07-11 21:43 UTC, Rubberbandits commented
> We should add a check to each test for these calls that each event is emitted, as expected. This was from ToB feedback

This is true, and is the standard for pallets from Paritytech. They have some code in the collective pallet for checking emitted event history which is super helpful.

2023-07-19 09:42 UTC, fabhed commented
Love that this is being worked on so promptly after I mentioned it in Discord. This will make indexing the chain much nicer!

2023-08-14 16:54 UTC, camfairchild approved these changes

2024-02-05 18:08 UTC, closed without merging