Ostraca
RaoFoundation/subtensor pull request #195
Opened 2023-11-10 18:29 UTC by unconst

2023-11-13 19:23 UTC, Rubberbandits requested changes

2023-11-13 19:23 UTC, Rubberbandits commented on pallets/subtensor/src/lib.rs
> +        #[pallet::weight((Weight::from_ref_time(14_000_000)
This will need to be benchmarked

2023-11-29 21:42 UTC, Rubberbandits approved these changes
After adding dynamic weight to ostraca function, and fixing unit testing, LGTM

2023-11-29 21:44 UTC, welikethestock approved these changes
Good to go

2024-03-27 16:44 UTC, closed without merging