Adds a migration to reset the Total Issuance value
RaoFoundation/subtensor pull request #254
Opened 2024-03-12 19:01 UTC by unconst

The general process is the following:

1. Fix the incorrect places where a burn is occuring in the code.
2. Add a migration which will re set the total issuance by summing up the balances, stake values and lock values.
3. Adds tests here for all three types of account balances.

2024-03-12 20:32 UTC, sam0x17 approved these changes
LGTM 🎉

2024-03-13 19:00 UTC, shibshib commented on pallets/subtensor/src/utils.rs
> +    pub fn mint_tokens(amount: u64 ){
This sort of naming might freak people out. Maybe let's just rename it to `update_totalissuance` or something

2024-03-13 19:00 UTC, shibshib commented on pallets/subtensor/src/block_step.rs
> +                Self::mint_tokens( cut.to_num::<u64>() );
Same comment as below, 'minting' should be reworded to something less defi-sounding.

2024-03-13 19:00 UTC, shibshib commented on pallets/subtensor/src/registration.rs
> +        Self::mint_tokens( 100_000_000_000 ); // Accounting here for the newly created tokens.
Why is the total issuance being updated here?

2024-03-13 19:11 UTC, unconst commented on pallets/subtensor/src/registration.rs
> +        Self::mint_tokens( 100_000_000_000 ); // Accounting here for the newly created tokens.
because this is the faucet.

2024-03-13 19:11 UTC, unconst commented on pallets/subtensor/src/block_step.rs
> +                Self::mint_tokens( cut.to_num::<u64>() );
ok. legal.

2024-03-13 19:12 UTC, unconst commented on pallets/subtensor/src/utils.rs
> +    pub fn mint_tokens(amount: u64 ){
ok big brother

2024-03-13 20:41 UTC, sam0x17 commented on pallets/subtensor/src/utils.rs
> +    pub fn mint_tokens(amount: u64 ){
`update_total_issuance` imo

2024-03-14 16:26 UTC, sam0x17 requested changes

2024-03-14 16:26 UTC, sam0x17 commented on pallets/subtensor/src/migration.rs
> +        let total_balance_sum: u64 = total_balance.try_into().unwrap_or_else(|_| panic!("Conversion must be within range"));
honestly this panic is really scary, could we just keep with the type of `T::Currency::total_issuance()` instead or does it not support the ops we need? (another reason to use my currencies crate in the future hahaha)

2024-04-02 19:25 UTC, sam0x17 approved these changes

2024-04-03 17:29 UTC, shibshib approved these changes

2024-04-03 17:30 UTC, merged