Hotfix/no registration no emission
RaoFoundation/subtensor pull request #474
Opened 2024-05-25 17:29 UTC by distributedstatemachine

## Description

This PR burns emissions for subnets that has registration turned off 

## Related Issue(s)

- Closes #[issue number]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-05-27 09:34 UTC, orriin approved these changes

2024-05-27 12:53 UTC, camfairchild requested changes
Looks good other than an extra test

2024-05-27 12:53 UTC, camfairchild commented on pallets/subtensor/tests/block_step.rs
Please add a test here for the on-Subnet turning them off before the next epoch.

We should see the emissions not load

2024-05-27 14:15 UTC, camfairchild approved these changes

2024-05-27 15:15 UTC, merged

2024-06-13 14:00 UTC, keithtensor commented on pallets/subtensor/tests/block_step.rs
> +        SubtensorModule::drain_emission(next_block as u64);
This is casting a function pointer to a `u64`, did you really mean to call `next_block()` here?