fix
RaoFoundation/subtensor pull request #527
Opened 2024-06-13 00:35 UTC by JohnReedV

## Description

## Related Issue(s)

- Closes #[issue number]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-06-13 01:31 UTC, sam0x17 approved these changes, later dismissed

2024-06-13 01:59 UTC, open-junius submitted a review, later dismissed

2024-06-13 21:23 UTC, sam0x17 approved these changes, later dismissed

2024-06-14 11:41 UTC, open-junius commented
we can merge it, PR in bittensor https://github.com/opentensor/bittensor/pull/2021 will fix the failed test case.

2024-06-14 16:29 UTC, distributedstatemachine approved these changes, later dismissed

2024-06-14 16:33 UTC, camfairchild approved these changes

2024-06-14 16:41 UTC, camfairchild requested changes, later dismissed

2024-06-14 16:41 UTC, camfairchild commented on pallets/subtensor/tests/block_step.rs
>          SubtensorModule::drain_emission(next_block as u64);
```suggestion
        SubtensorModule::drain_emission(block as u64);
```

2024-06-14 16:41 UTC, camfairchild commented on pallets/subtensor/tests/block_step.rs
> +        #[allow(clippy::fn_to_numeric_cast)]
```suggestion
```

2024-06-14 16:41 UTC, camfairchild commented on pallets/subtensor/tests/block_step.rs
> +        #[allow(clippy::fn_to_numeric_cast)]
we shouldn't be casting any functions

2024-06-14 16:41 UTC, camfairchild commented on pallets/subtensor/tests/block_step.rs
>          SubtensorModule::drain_emission(next_block as u64);
perhaps this was meant to be block

2024-06-14 17:00 UTC, camfairchild approved these changes

2024-06-14 17:13 UTC, distributedstatemachine approved these changes

2024-06-14 18:15 UTC, sam0x17 approved these changes

2024-06-14 20:00 UTC, merged