Document production profile
RaoFoundation/subtensor pull request #565
Opened 2024-06-24 11:02 UTC by orriin

Benchmark and production docs updated to use production profile.

Dev / testing / localnet can remain release profile. 

Also removes deprecated --execution args.

TODO: Devnet companion PR

2024-06-24 11:05 UTC, distributedstatemachine requested changes

2024-06-24 11:05 UTC, distributedstatemachine commented on scripts/benchmark.sh
> +  --execution=native --wasm-execution=compiled \
`--execution=native` can we take it out since its currently a noop and would soon be deprecated

2024-06-24 15:46 UTC, distributedstatemachine approved these changes

2024-06-24 15:52 UTC, JohnReedV approved these changes

2024-06-24 16:20 UTC, rajkaramchedu approved these changes

2024-06-24 17:12 UTC, sam0x17 approved these changes

2024-06-27 13:52 UTC, open-junius approved these changes

2024-06-28 17:10 UTC, merged