Clean the Subtensor Repo
RaoFoundation/subtensor pull request #638
Opened 2024-07-15 20:33 UTC by unconst

## Description
Reorgs the Subtensor Repo on main.

2024-07-15 20:37 UTC, distributedstatemachine submitted a review, later dismissed

2024-07-15 21:01 UTC, keithtensor commented on pallets/subtensor/src/coinbase/root.rs
> +        TotalNetworks::<T>::mutate(|n| *n = n.saturating_add(1));
Why change this?

2024-07-15 21:11 UTC, camfairchild commented on pallets/subtensor/src/coinbase/root.rs
> -        );
Make sure to add this back in some way

2024-07-16 14:54 UTC, open-junius commented on pallets/subtensor/src/macros/dispatches.rs
> +mod dispatches {
can we reset all the extrinsic's call_index, make them in order. don't know how to choose the next call index when add a new extrinsic

2024-07-17 14:49 UTC, gztensor requested changes

2024-07-17 14:49 UTC, gztensor commented on pallets/subtensor/src/lib.rs
> +    /// Total Rao in circulation.
This is inaccurate. According to coinmarketcap, we only have 7M TAO in circulation, and this value can change, it cannot be hardcoded.

2024-07-17 14:49 UTC, gztensor commented on pallets/subtensor/src/macros/dispatches.rs
> +            Ok(())
Is it more user friendly to remove this extrinsic? Users may think it succeeded if they call it with btcli.

2024-07-17 14:49 UTC, gztensor commented on pallets/subtensor/src/macros/hooks.rs
> +            weight = weight
Since we're cleaning up, we should remove migrations that have already happened.

2024-07-17 14:49 UTC, gztensor commented on pallets/subtensor/src/staking/helpers.rs
> +        for (delegate_coldkey_i, stake_i) in
We should probably introduce some minimum stake to protect Stake map from dust

2024-07-23 18:39 UTC, closed without merging