custom lints / freeze struct improvements
RaoFoundation/subtensor pull request #724
Opened 2024-08-08 04:36 UTC by sam0x17

## Description

## Related Issue(s)

- Closes #[issue number]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-08-14 17:35 UTC, sam0x17 commented
closing since swap insertion isn't really an issue anymore 🎉 


will pull out some of the changes here since there were some unrelated improvements

2024-08-14 17:35 UTC, sam0x17 commented
whoops

2024-08-16 12:35 UTC, distributedstatemachine requested changes

2024-08-16 12:35 UTC, distributedstatemachine commented on scripts/localnet.sh
> +  cargo build --workspace --profile=production --features "$FEATURES" --manifest-path "$BASE_DIR/Cargo.toml"
We do not want these for local net builds , as it just makes it alot longer. I think the original release build is sufficient

2024-08-16 12:35 UTC, distributedstatemachine commented on support/linting/src/dummy_lint.rs
> +impl Lint for DummyLint {
Why do we need DummyLint?

2024-08-16 12:49 UTC, sam0x17 commented on support/linting/src/dummy_lint.rs
> +impl Lint for DummyLint {
we can probably remove it now good call out lol

2024-08-16 15:29 UTC, distributedstatemachine approved these changes

2024-08-16 16:56 UTC, unconst approved these changes

2024-08-16 16:57 UTC, merged