Mz/feat/staking precompile
RaoFoundation/subtensor pull request #777
Opened 2024-09-04 21:22 UTC by DedicatedDev

## Description

##Key changes
 - added staking precompile to runtime 

## Related Issue(s)

- Closes #[issue number]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-09-04 21:58 UTC, gztensor requested changes

2024-09-04 21:58 UTC, gztensor commented on runtime/src/precompiles/staking.rs
> +                handle.context().caller,
`handle.context().caller` contains `msg.sender`, i.e. the address that called this contract. At the time when this method is called, the balance is already transferred to this precompile address, but `pallet_subtensor::Call::<Runtime>::add_stake` will attempt to remove it again from the `handle.context().caller` account. 

The amount needs to be transferred back to `handle.context().caller` before calling `add_stake`.

2024-09-05 10:32 UTC, soring323 commented on runtime/src/precompiles/staking.rs
> +                handle.context().caller,
Great Catch. 
added refund logic and tested. 
Thank you

2024-09-05 16:08 UTC, gztensor approved these changes

2024-09-05 16:09 UTC, merged