Per-subnet registration allowance
RaoFoundation/subtensor pull request #78
Opened 2023-03-23 21:05 UTC by Rubberbandits

This PR allows subnets to allow/disallow registration to it through a sudo call.

2023-04-13 14:15 UTC, SaMotlagh requested changes

2023-04-13 14:15 UTC, SaMotlagh commented on pallets/subtensor/src/lib.rs
> +
- we need to add index for each call. that would be nice if you add this call at the end and increment index. 
- Also, you could run benchmark fn for this call and see how many r/w it needs. it must be similar to other calls and need one r/w. If so, I recommend to add similar weights for it.

2023-05-31 02:02 UTC, camfairchild requested changes
Needs a test for new sudo call, should check if registration fails with it set to `False`

2023-05-31 18:19 UTC, Rubberbandits reviewed
LGTM

2023-05-31 18:19 UTC, shibshib approved these changes

2023-05-31 18:32 UTC, merged