Check for childkey stake when setting weights
RaoFoundation/subtensor pull request #924
Opened 2024-11-06 15:03 UTC by keithtensor

Resolves #917.

2024-11-06 15:48 UTC, gztensor requested changes

2024-11-06 15:48 UTC, gztensor commented on pallets/subtensor/src/lib.rs
> +        pub fn check_weights_min_stake(hotkey: &T::AccountId, netuid: u16) -> bool {
We should also consider stake that this hotkey gives to children, not only the one it receives from parents. There's a `get_stake_for_hotkey_on_subnet` function in `run_epoch.rs` that implements that. I think we should use it all over instead of `get_total_stake_for_hotkey` for this feature.

2024-11-07 14:55 UTC, gztensor approved these changes

2024-11-07 15:05 UTC, camfairchild approved these changes

2024-11-07 19:43 UTC, unconst approved these changes

2024-11-07 19:43 UTC, merged