Fix/childkey emission distibution
RaoFoundation/subtensor pull request #950
Opened 2024-11-08 17:28 UTC by gztensor

## Description
Fixes hotkey draining issues:
1. Miner emission should not be distributed to nominators
2. Childkey take should not be distributed to nominators

## Related Issue(s)

- Closes #855 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

n/a

## Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-08 21:06 UTC, sam0x17 approved these changes, later dismissed

2024-11-12 17:40 UTC, camfairchild requested changes

2024-11-12 17:40 UTC, camfairchild commented on pallets/subtensor/src/coinbase/run_coinbase.rs
> +        let childkey_take_proportion: I64F64 =
This precision differs from the later use when multiplying on 233

2024-11-12 17:55 UTC, gztensor commented on pallets/subtensor/src/coinbase/run_coinbase.rs
> +        let childkey_take_proportion: I64F64 =
`childkey_take_proportion` value is between 0 and 1, and we're multiplying u64 parent_emission by this value. Looks ok to me. Is there anything wrong there?

2024-11-12 19:52 UTC, camfairchild submitted a review, later dismissed
approved with a nit

2024-11-12 19:52 UTC, camfairchild commented on pallets/subtensor/src/coinbase/run_coinbase.rs
> +                    .to_num::<u64>();
probably shouldn't cast here (keep as a float). Maybe only cast the final results.

2024-11-13 00:08 UTC, camfairchild approved these changes, later dismissed

2024-11-14 15:04 UTC, sam0x17 approved these changes

2024-11-14 15:23 UTC, camfairchild approved these changes

2024-11-14 15:23 UTC, camfairchild commented on pallets/subtensor/tests/children.rs
> +        // Run run_coinbase until PendingHotkeyEmission is drained for both child and parent
Nit: Why not just populate pendinghotkeyemission directly.

2024-11-15 18:27 UTC, merged