get stake interface in solidity
RaoFoundation/subtensor pull request #955
Opened 2024-11-12 10:24 UTC by open-junius

## Description
The PR add the stake data access in solidity precompile contract. 

## Related Issue(s)

- Closes #[857]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

2024-11-13 13:50 UTC, orriin reviewed
Looks good, can we get a test?

2024-11-13 14:09 UTC, open-junius commented
> Looks good, can we get a test?
Verified the interface via js code, let me push it into main branch of subtensor-js-tests.

2024-12-06 00:01 UTC, gztensor commented
Please implement the e2e test for this as a separate test and let it fail. When we merge to devnet-ready, the tests will be passing.

2024-12-06 12:41 UTC, open-junius commented
https://github.com/opentensor/subtensor-js-tests/blob/main/src/evm/eth.staking.precompile.test.js#L215 separate test case is added.

2024-12-18 18:16 UTC, kyriediculous commented
It would be great to have this merged ! Thanks for this PR.

2024-12-18 18:33 UTC, sam0x17 approved these changes

2025-01-02 20:56 UTC, sam0x17 submitted a review, later dismissed

2025-01-02 22:23 UTC, gztensor approved these changes, later dismissed

2025-01-02 22:27 UTC, camfairchild requested changes

2025-01-02 22:27 UTC, camfairchild commented on runtime/src/precompiles/solidity/staking.sol
> +  function getStake(bytes32 hotkey, bytes32 coldkey) external view returns (uint64);
```suggestion
  function getStake(bytes32 hotkey, bytes32 coldkey, uint16 netuid) external view returns (uint64);
```

2025-01-02 22:27 UTC, camfairchild commented on runtime/src/precompiles/solidity/staking.sol
> +   * @param coldkey The coldkey public key (32 bytes).
```suggestion
   * @param coldkey The coldkey public key (32 bytes).
   * @param netuid The subnet the stake is on (uint16).
```

2025-01-02 22:27 UTC, camfairchild commented on runtime/src/precompiles/staking.rs
> +            id if id == get_method_id("getStake(bytes32,bytes32)") => {
```suggestion
            id if id == get_method_id("getStake(bytes32,bytes32,uint16)") => {
```

2025-01-02 22:27 UTC, camfairchild commented
Needs the `netuid` param for RAO future-proofing

2025-01-03 11:21 UTC, open-junius commented
> Needs the `netuid` param for RAO future-proofing

Will update it after RAO feature merged. Now, we can use the netuid in nowhere.

2025-01-14 19:10 UTC, sam0x17 approved these changes

2025-01-14 19:10 UTC, merged